
spring:
  datasource:
      url: jdbc:mysql://localhost:3307/shiroback?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: 123456
mybatis:
   mapperLocations: classpath:/mapper/*.xml
#server:
#  port: 8084
