# 项目相关配置
javaniuniu:
  # 名称
  name: javaniuniu
  # 版本
  version: 1.0
  # 版权年份
  copyrightYear: 2020
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/javaniuniu/uploadPath，Linux配置 /home/javaniuniu/uploadPath）
  profile: /Users/minp/GitHub/springboot-buckets/springboot-thread-async/uploadPath
  # 获取ip地址开关
  addressEnabled: true