
##########################################################
##################  所有profile共有的配置  #################
##########################################################

###################  spring配置  ###################
spring:
  profiles:
    active: dev

---

#####################################################################
########################  开发环境profile  ##########################
#####################################################################
spring:
  profiles: dev
  data:
    mongodb:
      uri: mongodb://javaniuniu:123456@localhost:27018/test

logging:
  level:
    ROOT: INFO
    com:
      xncoding: DEBUG
  file: /Users/minp/GitHub/springboot-buckets/springboot-mongodb/logs/app.log
